package view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author coelh
 */
public class FrameApp extends javax.swing.JFrame {
    private static JPanel painelPrincipalTroca;
    private static JScrollPane painelRolagem;
    private static CardLayout gerenciadorPaineis;
    static HashMap<String, JPanel> tabelaPaineisAtivos;
    
    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        meuInitComponents();
    }
    
    public void meuInitComponents(){
        tabelaPaineisAtivos = new HashMap<>();
        this.setLayout(new BorderLayout());
        
        this.painelRolagem = new JScrollPane();
        this.gerenciadorPaineis = new CardLayout();
        this.painelPrincipalTroca = new JPanel(gerenciadorPaineis);
        
        this.add(this.painelRolagem, BorderLayout.CENTER);
        this.painelRolagem.setViewportView(this.painelPrincipalTroca);
        
        trocaPainel(new Login(), "Login");

    }
    
    public static void trocaPainel(JPanel p, String nomeP){
        if(tabelaPaineisAtivos.containsKey(nomeP)){
            gerenciadorPaineis.show(painelPrincipalTroca, nomeP);
            painelPrincipalTroca.setPreferredSize(tabelaPaineisAtivos.get(nomeP).getPreferredSize());
        }else{
            painelPrincipalTroca.add(p, nomeP);
            gerenciadorPaineis.show(painelPrincipalTroca, nomeP);
            painelPrincipalTroca.setPreferredSize(p.getPreferredSize());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
